image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2375
stages:
  - build
  - package

build-prod:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean
    - mvn compile
    - mvn package
  artifacts:
    paths:
      - target/*.war
      - Dockerfile
    expire_in: 60min
  only:
    - main

package-prod:
  image: 
    name: docker:stable
  stage: package
  services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

  before_script:
    - docker --version
    # - until docker info; do sleep 1; done
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t abcd .
    - docker tag abcd sayederfanarefin/database-hackathon:latest
    - docker push sayederfanarefin/database-hackathon:latest
  only:
    - main
