version: '3'

services:
  app:
    image: erfanarefin/database-hackathon:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/www/html/upload-dir:/upload-dir
      - /var/www/html/upload-dir-admin:/upload-dir-admin

    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: 3306
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

    ports:
      - 3306:3306

    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: