version: '3'

services:
  app:
    image: sayederfanarefin/database-hackathon:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/www/html/upload-dir:/upload-dir
      - /var/www/html/upload-dir-admin:/upload-dir-admin
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # User admin environment variables
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_FIRSTNAME: ${ADMIN_FIRSTNAME}
      ADMIN_LASTNAME: ${ADMIN_LASTNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      
      # Regular user environment variables
      USER_USERNAME: ${USER_USERNAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_FIRSTNAME: ${USER_FIRSTNAME}
      USER_LASTNAME: ${USER_LASTNAME}
      USER_PASSWORD: ${USER_PASSWORD}
      
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.0.1
    # image: mysql:latest
    platform: linux/arm64/v8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}  # Regular user (not root)
      MYSQL_PASSWORD: ${DB_PASSWORD}  # Regular user password
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Root password
    ports:
      - 3306:3306
    volumes:
      - db-data:/Users/sayederfanarefin/Desktop/mysql-stuff
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db-data:
